[project]
name = "one-billion-row-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.2.2",
    "pandas>=2.2.3",
    "polars>=1.27.0",
    "tqdm>=4.67.1",
]
